In [0]:
from numpy import linalg as LA 
import matplotlib.pyplot as plt
import numpy as np
from numpy import linalg as LA
from sklearn.metrics import mean_squared_error

In [39]:
#Part a) Find the sample mean

sample = [[3,2,1],[2,4,5],[1,2,3],[0,2,5]]

sample_mean = np.mean(sample, axis=0)
print("Sample Mean: ",sample_mean)

Sample Mean:  [1.5 2.5 3.5]


In [40]:
# Partb) Center data around mean by subtracting it from all samples
sample_centered = sample - np.mean(sample, axis=0)
sample_centered

array([[ 1.5, -0.5, -2.5],
       [ 0.5,  1.5,  1.5],
       [-0.5, -0.5, -0.5],
       [-1.5, -0.5,  1.5]])

In [41]:
# Part b) Find the sample covariance matrix Q
m, n = np.shape(X)
data_adjust = []
avgs = np.tile(sample_mean, (m, 1))
data_adjust = X - avgs
covX = np.cov(data_adjust.T)  
print("Sample Covariance: \n",covX)

Sample Covariance: 
 [[ 1.66666667  0.33333333 -1.66666667]
 [ 0.33333333  1.          1.        ]
 [-1.66666667  1.          3.66666667]]


In [42]:
#Part b) Find the eigenvalues and eigenvectors.
featValue, featVec=  np.linalg.eig(covX)  
print("\n Eigenvalues: \n",featValue)
print("\n Eigenvectors: \n",featVec)


 Eigenvalues: 
 [4.74888619 1.56450706 0.01994008]

 Eigenvectors: 
 [[-0.45056922 -0.66677184 -0.59363515]
 [ 0.19247228 -0.72187235  0.66472154]
 [ 0.87174641 -0.18524476 -0.45358856]]


In [43]:
#Part c) PCA without using sklearn
# Observe variance along eigenvectors obtained
total = sum(featValue)
var_exp = [(i / total)*100 for i in sorted(featValue, reverse = True)]
cum_var_exp = np.cumsum(var_exp)
print(cum_var_exp)

[ 74.98241353  99.6851566  100.        ]


Observe that the first two Eigenvectors capture most of the variance in the data. 



In [44]:

# Part c) Finding PCA coefficients corresponding to each of the samples by choosing the top two eigenvectors
top2_vectors = featVec[:,0:2]
projection = sample_centered.dot(top2_vectors)
print("PCA Coefficients corresponding to each of the samples: \n",projection)

PCA Coefficients corresponding to each of the samples: 
 [[-2.95145599 -0.17610969]
 [ 1.37104342 -1.69406159]
 [-0.30682473  0.78694448]
 [ 1.8872373   1.0832268 ]]


In [45]:
#Part d) Reconstructing the original samples
sample_reconstructed = projection.dot(top2_vectors.T) + sample_mean
print("Reconstructed Sample: \n",sample_reconstructed)

# Calculate reconstruction error

reconstruction_error = ((sample_centered - sample_reconstructed)**2)
print("\n Reconstruction Error: \n",reconstruction_error)

print("\n Mean Reconstruction Error: \n", mean_squared_error(sample, sample_reconstructed))

Reconstructed Sample: 
 [[ 2.94726021  2.05905526  0.95970224]
 [ 2.0118026   3.98678407  5.0090182 ]
 [ 1.11353336  1.87287129  3.0867493 ]
 [-0.07259617  2.08128939  4.94453025]]

 Reconstruction Error: 
 [[ 2.09456211  6.5487638  11.9695396 ]
 [ 2.28554709  6.18409501 12.31320875]
 [ 2.60348992  5.63051814 12.86477056]
 [ 2.03748169  6.66305491 11.86478866]]

 Mean Reconstruction Error: 
 0.004985020477602166
